name: babay_mobile
description: "A coupon app for markets, cafes, and other retail establishments."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  mobile_scanner: ^4.0.0
  permission_handler: ^11.3.0
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7
  modal_bottom_sheet: ^3.0.0
  http: ^1.2.1
  dio: ^5.4.1
  pinput: ^4.0.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  provider: ^6.1.2
  logger: ^2.5.0
  flutter_svg: ^2.0.10
  intl: ^0.19.0
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
